Add retry feature for HTTPRequest::get()
wazuh/wazuh-http-request pull request #25
Opened 2023-02-02 13:32 UTC by tsarquis88

| Issue |
| --- |
| Closes #24 |

### Description
This PR adds the capability of re-try the HTTP GET process when it fails.

The number of attempts is easily modifiable. It's defined [here](https://github.com/wazuh/wazuh-http-request/blob/retry-http-get/src/HTTPRequest.cpp#L66).

2023-02-02 13:34 UTC, tsarquis88 commented on test/component/component_test.cpp
> +TEST_F(ComponentTestInterface, GetIncorrectPort)
This test is not directly related to this PR but it was useful to see that the exception is thrown when all the attempts fail.

2023-02-02 14:36 UTC, tsarquis88 commented on test/benchmark/main.cpp
> +class BenchmarkFakeServer final
The naming changes are due to achieve cppcheck compliance.

2023-02-10 20:21 UTC, Damian-Mangold commented on src/HTTPRequest.cpp
> +    // Do fetchAttempts attempts to fetch the description
The description seems very specific to me, it will make two attempts on each get, no matter what content is trying to get.

2023-02-10 20:21 UTC, Damian-Mangold commented on test/benchmark/main.cpp
> +class BenchmarkFakeServer final
I see this as an improvement and beyond the scope of the issue. I think it would be convenient to open a specific topic to apply these changes.
But I don't know what you think @Dwordcito

2023-02-10 20:21 UTC, Damian-Mangold commented on test/component/component_test.hpp
> +class ComponentTestFakeServer;
I see this as an improvement and beyond the scope of the issue. I think it would be convenient to open a specific topic to apply these changes.
But I don't know what you think @Dwordcito

2023-02-10 20:21 UTC, Damian-Mangold commented on test/component/component_test.cpp
> +TEST_F(ComponentTestInterface, GetIncorrectPort)
I think these tests are valid and necessary since you changed the behavior logic of the get operation and you need to check it.

2023-02-14 09:29 UTC, tsarquis88 commented on src/HTTPRequest.cpp
> +    auto fetchAttempts {2};
Like it!

2023-02-14 09:41 UTC, tsarquis88 commented on test/benchmark/main.cpp
> +class BenchmarkFakeServer final
I managed to restore the benchmark fake server class name, but no luck with the component. Don't know why cppcheck didn't complaint before.

2023-02-14 12:03 UTC, Damian-Mangold commented on src/HTTPRequest.cpp
> +    // Do fetchAttempts attempts to fetch the description
I would remove the comment or make it more generic, something like that;

`try the request `getAttempts` times`

2023-02-14 12:11 UTC, tsarquis88 commented on src/HTTPRequest.cpp
> +    // Do fetchAttempts attempts to fetch the description
Understood!

2023-02-14 14:21 UTC, sebasfalcone requested changes

2023-02-14 14:21 UTC, sebasfalcone commented on src/HTTPRequest.cpp
> +    auto getAttempts {2};
Question (design): Instead of making this parameter fixed, we could add a second constructor that takes this value as a parameter, but also have a constructor without a parameter that sets this to a default value of... 2?

Any thoughts?

2023-02-14 14:21 UTC, sebasfalcone commented on src/HTTPRequest.cpp
> +            exceptionMessage = ex.what();
Improve (design): If the error message differs from one execution to the other, this will mask that.
I think we should capture all of them
```suggestion
            exceptionMessage += "'" + getAttempex.what() + "'. ";
```

2023-02-14 14:21 UTC, sebasfalcone commented on src/HTTPRequest.cpp
> +            exceptionMessage = ex.what();
An alternative is to save them in a vector but that involves a lot of changes

2023-02-14 14:21 UTC, sebasfalcone commented on test/component/component_test.cpp
> +    auto onErrorCallback {false};
improve (naming): I think the name is a bit me sliding, I thought it was an actual callback. What about errorCallbackExecuted

2023-02-14 15:03 UTC, tsarquis88 commented on src/HTTPRequest.cpp
> +    auto getAttempts {2};
I think modifying the constructor just to set a member that will be used in one method may be overkilling.

If in the future, the retry feature is present in all queries, this change could be interesting.

2023-02-14 15:11 UTC, tsarquis88 commented on src/HTTPRequest.cpp
> +            exceptionMessage = ex.what();
I find this request not very clean and/or scalable.

Also, the callback will receive a string of concatenated errors: complex to parse IMO (the caller should be responsible for how to log this error).

For N attempts, the resulting error would be:
```
"'Error 1 message'. 'Error 2 message'. ... 'Error N message'. "
```

2023-02-14 15:12 UTC, tsarquis88 commented on test/component/component_test.cpp
> +    auto onErrorCallback {false};
Agree! I will use `errorCallbackComplete` in order to be compliant with `m_callbackComplete` boolean.

2023-02-14 15:47 UTC, jftuduri commented on src/HTTPRequest.cpp
> +        }
The only concern I have (and not totally sure if matters or not) is that the catch will also catch exceptions thrown inside the `onSuccess` callback. That is, the get operation succeeds, the function calls onSuccess, onSuccess throws, the function catches and then repeats the get operation.

2023-02-14 16:55 UTC, sebasfalcone commented on src/HTTPRequest.cpp
> +    auto getAttempts {2};
The variable may be used in one method but this class is used in a lot of places. Maybe 2 getAttepts is enough for the scenario we are facing but is not enough in others

Another solution is to pass getAttemps on the get request as an optional argument and set that to 2 by default

2023-02-15 08:10 UTC, tsarquis88 commented on src/HTTPRequest.cpp
> +    auto getAttempts {2};
Like this last option!

2023-02-15 08:39 UTC, tsarquis88 commented on src/HTTPRequest.cpp
> +        }
Nice catch! 
I moved the `onSuccess` call outside the `try` scope.

2023-02-15 08:45 UTC, tsarquis88 commented on src/HTTPRequest.cpp
> +            exceptionMessage = ex.what();
Done.

2023-02-15 08:47 UTC, tsarquis88 commented on src/HTTPRequest.cpp
> +            exceptionMessage = ex.what();
[Here](https://github.com/wazuh/wazuh-http-request/blob/b36a0cc870f0d285bb1a3465df71756fd3760398/test/component/component_test.cpp#L108) is an example on how the message will be generated.

2023-02-15 12:00 UTC, sebasfalcone approved these changes
LGTM

2023-02-15 14:54 UTC, jftuduri commented on src/HTTPRequest.cpp
> +    // Try the request 'getAttempts' times
```suggestion
    // Try the request 'attempts' times
```

2023-02-15 14:54 UTC, jftuduri commented on src/HTTPRequest.cpp
> +            response = req.response();
Can we avoid this copy?
May be moving `auto req {GetRequest::builder(FactoryRequestWrapper<wrapperType>::create())};` out of the try and calling `onSuccess(req.response());` after the catch, and adding a `continue` in the catch block. Haven't tested it.

2023-02-15 14:54 UTC, jftuduri commented on test/component/component_test.cpp
> +        2); // This should be greater than one in order to success
Is it possible to add a test with a different `attempts` number? What happens if it is 0?

2023-02-16 10:21 UTC, tsarquis88 commented on src/HTTPRequest.cpp
> +            response = req.response();
Done!

2023-02-16 10:26 UTC, tsarquis88 commented on test/component/component_test.cpp
> +        2); // This should be greater than one in order to success
Nice question.

I'm thinking in:
- Throwing when `attempts` equals zero (or forcing it to be one).
- Changing `attempts` for `retryAttempts`: There's always one attempt no matter what, and if it fails we repeat the query `retryAttempts` times. Like that, `retryAttempts` could be zero (no retry).

2023-02-16 10:43 UTC, tsarquis88 commented on test/component/component_test.cpp
> +        2); // This should be greater than one in order to success
I've chosen the second option. It doesn't make sense to do a get with zero attempts.

2023-02-16 11:59 UTC, sebasfalcone commented on test/component/component_test.cpp
> +        2); // This should be greater than one in order to success
I've liked the approach

2023-02-16 12:03 UTC, sebasfalcone reviewed
I think that the change was in the right direction but need a bit o tweaking

2023-02-16 12:03 UTC, sebasfalcone commented on src/HTTPRequest.cpp
> +    while (firstGet || 0 < retryAttempts)
Improve (complexity): Create a new variable called attempts and initialize it with 1 + retryAttemps and maintain the old logic

2023-02-16 14:56 UTC, tsarquis88 commented on src/HTTPRequest.cpp
> +    while (firstGet || 0 < retryAttempts)
Nice! Done.

2023-02-16 15:21 UTC, jftuduri submitted a review, later dismissed

2023-02-16 15:36 UTC, sebasfalcone submitted a review, later dismissed
👒 👌🏼

2023-02-22 09:13 UTC, tsarquis88 commented on src/UNIXSocketRequest.cpp
> +    // TODO: Implement retry attempts logic
I did so because the issue is related to `HTTPRequest` and not `UNIXSocketRequest`.

2023-02-22 15:22 UTC, Damian-Mangold commented on src/UNIXSocketRequest.cpp
> +    // TODO: Implement retry attempts logic
Yes, I get it, but touching the `IURLRequest` interface affects the `UNIXSocketRequest` class and I feel uncomfortable leaving an implementation unrealized. Maybe we should create a specific issue for this. What do you think @Dwordcito ?

2023-03-01 07:56 UTC, tsarquis88 commented on src/UNIXSocketRequest.cpp
> +    // TODO: Implement retry attempts logic
I've added the feature to this class as well. The problem is that is not tested anywhere.

2023-03-01 11:59 UTC, jftuduri approved these changes

2023-03-01 17:25 UTC, sebasfalcone submitted a review, later dismissed

2023-04-21 16:29 UTC, Dwordcito requested changes

2023-04-21 16:29 UTC, Dwordcito commented on src/HTTPRequest.cpp
> +    unsigned int attempts {1 + retryAttempts};
```suggestion
    unsigned int attempts {1u + retryAttempts};
```

2023-04-21 16:29 UTC, Dwordcito commented on src/HTTPRequest.cpp
> +    while (0 < attempts)
```suggestion
    while (0u < attempts)
```

2023-04-21 16:29 UTC, Dwordcito commented on src/HTTPRequest.cpp
> +    if (0 == attempts)
```suggestion
    if (0u == attempts)
```

2023-04-21 16:29 UTC, Dwordcito commented on src/HTTPRequest.cpp
> +            attempts--;
Pre decrements have fewer instructions.
```suggestion
            --attempts;
```

2023-04-21 16:29 UTC, Dwordcito commented on src/UNIXSocketRequest.cpp
> +    unsigned int attempts {1 + retryAttempts};
ditto

2023-04-21 16:29 UTC, Dwordcito commented on src/UNIXSocketRequest.cpp
> +    while (0 < attempts)
ditto

2023-04-21 16:29 UTC, Dwordcito commented on src/UNIXSocketRequest.cpp
> +    if (0 == attempts)
ditto

2023-04-21 16:29 UTC, Dwordcito commented on src/UNIXSocketRequest.cpp
> +            attempts--;
ditto

2023-04-21 16:29 UTC, Dwordcito commented on include/UNIXSocketRequest.hpp
> +        const unsigned int retryAttempts = 1);
no retry as default value.

```suggestion
        const unsigned int retryAttempts = 0);
```

2023-04-21 16:29 UTC, Dwordcito commented on include/IURLRequest.hpp
> +        const unsigned int retryAttempts = 1) = 0;
no retry as default value.

```suggestion
        const unsigned int retryAttempts = 0) = 0;
```

2023-04-21 16:29 UTC, Dwordcito commented on include/HTTPRequest.hpp
> +        const unsigned int retryAttempts = 1);
no retry as default value.

```suggestion
        const unsigned int retryAttempts = 0);
```

2023-04-21 16:29 UTC, Dwordcito commented on include/HTTPRequest.hpp
> +     * @param retryAttempts Number of retry attempts if the query fails.
extend the message to explain the default value.

2023-05-04 07:23 UTC, closed without merging