Secure communication capabilities
wazuh/wazuh-http-request pull request #46
Opened 2023-10-31 13:59 UTC by MiguelazoDS

# Description 

This PR adds the required changes to connect to a secure server with basic and client authentication.

2023-10-31 20:58 UTC, diegodfrf requested changes

2023-10-31 20:58 UTC, diegodfrf commented on include/HTTPRequest.hpp
> +        const std::unordered_set<std::string>& httpHeaders = std::unordered_set<std::string>(),
Isn't it better ?
```suggestion
        const std::unordered_set<std::string>& httpHeaders = {};
```

2023-10-31 20:58 UTC, diegodfrf commented on include/IURLRequest.hpp
> +        const std::unordered_set<std::string>& httpHeaders = std::unordered_set<std::string>(),
Isn't it better ?
```suggestion
        const std::unordered_set<std::string>& httpHeaders = {};
```

2023-10-31 20:58 UTC, diegodfrf commented on include/secureCommunication.hpp
> +    SecureCommunication(const std::string& caRootCertificate)
```suggestion
    SecureCommunication(const std::string& caRootCertificate):
    m_caRootCertificate{caRootCertificate}
```

2023-11-01 18:27 UTC, MiguelazoDS commented on include/HTTPRequest.hpp
> +        const std::unordered_set<std::string>& httpHeaders = std::unordered_set<std::string>(),
That was implemented prior to this PR but it's a good catch to use the constructor by default. Changed.

2023-11-01 18:28 UTC, MiguelazoDS commented on include/IURLRequest.hpp
> +        const std::unordered_set<std::string>& httpHeaders = std::unordered_set<std::string>(),
Ditto

2023-11-01 18:28 UTC, MiguelazoDS commented on include/secureCommunication.hpp
> +    SecureCommunication(const std::string& caRootCertificate)
Changed

2023-11-01 18:33 UTC, diegodfrf approved these changes

2023-11-05 21:10 UTC, merged