Implement curl multi handler
wazuh/wazuh-http-request pull request #50
Opened 2024-01-03 12:56 UTC by kevin-mcm

| Issue |
| --- |
|Closes #49 |

## Description
This PR aims to add a curl multi handler class. To achieve this, a refactoring of the previous implementation was done by adding a class that contains the single handler and multi handler along with the thread ID. This class is responsible for creating and storing a single handler and multi-handler for each thread ID. Additionally, the tests and benchmarks were updated.

2024-01-03 15:30 UTC, tsarquis88 requested changes
Partial review!

2024-01-03 15:30 UTC, tsarquis88 commented on include/curlSingleHandler.hpp
> +        const auto resGetInfo = curl_easy_getinfo(m_curlHandler.get(), CURLINFO_RESPONSE_CODE, &responseCode);
Brace initialization
```suggestion
        const auto resGetInfo {curl_easy_getinfo(m_curlHandler.get(), CURLINFO_RESPONSE_CODE, &responseCode)};
```

2024-01-03 15:30 UTC, tsarquis88 commented on include/ICURLHandler.hpp
> + */
Missing `@brief`
```suggestion
/**
 * @brief This class serves as the interface that represents a curl handler.
 */
```

2024-01-03 15:30 UTC, tsarquis88 commented on include/ICURLHandler.hpp
> + */
Same for the other new files.

2024-01-03 15:30 UTC, tsarquis88 commented on include/curlMultiHandler.hpp
> +     * @brief This method performs the request.
Same as above
```suggestion
     * @brief Performs the request.
```

2024-01-03 15:30 UTC, tsarquis88 commented on include/curlMultiHandler.hpp
> +        CURLMcode multiCode = curl_multi_add_handle(m_curlMultiHandler.get(), m_curlHandler.get());
Use auto and brace initialization
```suggestion
        auto multiCode {curl_multi_add_handle(m_curlMultiHandler.get(), m_curlHandler.get())};
```

2024-01-03 15:30 UTC, tsarquis88 commented on include/curlMultiHandler.hpp
> +        const auto resGetInfo = curl_easy_getinfo(m_curlHandler.get(), CURLINFO_RESPONSE_CODE, &responseCode);
Brace initialization
```suggestion
        const auto resGetInfo {curl_easy_getinfo(m_curlHandler.get(), CURLINFO_RESPONSE_CODE, &responseCode)};
```

2024-01-03 15:30 UTC, tsarquis88 commented on include/HTTPRequest.hpp
> +    void customDownload(
Question: Why are we just implementing the GET query for multi-handlers and not the rest of the queries (POST; PATCH, etc.)?

2024-01-03 15:30 UTC, tsarquis88 commented on src/HTTPRequest.cpp
> +void HTTPRequest::customDownload(const URL& url,
Question: Isn't there a mechanism to interrupt the download?

2024-01-04 01:29 UTC, kevin-mcm commented on include/ICURLHandler.hpp
> +     * @brief This method performs the request.
done

2024-01-04 01:29 UTC, kevin-mcm commented on include/ICURLHandler.hpp
> +     * @return std::shared_ptr<CURL>
done

2024-01-04 01:29 UTC, kevin-mcm commented on include/ICURLHandler.hpp
> +     * @return CurlHandlerTypeEnum
done

2024-01-04 01:29 UTC, kevin-mcm commented on include/ICURLHandler.hpp
> +    CurlHandlerTypeEnum m_curlHandlerType; ///< Enum value for this curl handler type.
done

2024-01-04 01:29 UTC, kevin-mcm commented on include/curlSingleHandler.hpp
> +        const auto resGetInfo = curl_easy_getinfo(m_curlHandler.get(), CURLINFO_RESPONSE_CODE, &responseCode);
done

2024-01-04 01:29 UTC, kevin-mcm commented on include/ICURLHandler.hpp
> + */
done

2024-01-04 01:29 UTC, kevin-mcm commented on include/curlMultiHandler.hpp
> +     * @brief This method performs the request.
done

2024-01-04 01:29 UTC, kevin-mcm commented on include/curlMultiHandler.hpp
> +        CURLMcode multiCode = curl_multi_add_handle(m_curlMultiHandler.get(), m_curlHandler.get());
done

2024-01-04 01:29 UTC, kevin-mcm commented on include/curlMultiHandler.hpp
> +        const auto resGetInfo = curl_easy_getinfo(m_curlHandler.get(), CURLINFO_RESPONSE_CODE, &responseCode);
done

2024-01-04 01:31 UTC, kevin-mcm commented on src/HTTPRequest.cpp
> +void HTTPRequest::customDownload(const URL& url,
done
> I forgot to include it as part of the initial commit 😶‍🌫️

2024-01-04 17:41 UTC, Damian-Mangold commented on include/HTTPRequest.hpp
> +    void customDownload(
I think it would be convenient that all queries have this functionality. And I do not see convenient to create a new method, it would be necessary to modify the current ones with the default values.

2024-01-05 11:47 UTC, jftuduri submitted a review, later dismissed
Partial review

2024-01-05 11:47 UTC, jftuduri commented on include/curlMultiHandler.hpp
> +                std::this_thread::sleep_for(std::chrono::milliseconds(100));
Question: is this wait necessary? I understand curl_multi_wait will wait for CURL_MULTI_HANDLER_TIMEOUT_MS for any activity.

2024-01-05 11:47 UTC, jftuduri commented on include/HTTPRequest.hpp
> +     * @param shouldRun Flag used to interrupt the handler.
With the current implementation the `shouldRun` flag only works if the `handlerType` is `MULTI`. I don't see that mentioned anywhere.
Some options that come to mind:
- Change the interface so that the handlerType is inferred on whether a shouldRun flag is passed in.
- In the implementation throw exception/error if handlerType is MULTI and a shouldRun flag is passed in (it will requires changes to detect that)
- Clearly state this limitation in the documentation.

Do you see any other option?

2024-01-05 12:09 UTC, kevin-mcm commented on include/curlMultiHandler.hpp
> +                std::this_thread::sleep_for(std::chrono::milliseconds(100));
that's true, in this case, it's not necessary. 
I'll remove it

2024-01-05 12:15 UTC, kevin-mcm commented on include/HTTPRequest.hpp
> +     * @param shouldRun Flag used to interrupt the handler.
I'll add it to the documentation. 

> In the implementation throw exception/error if handlerType is MULTI and a shouldRun flag is passed in (it will requires changes to detect that)

do you mean when the `handlerType` is **SINGLE** and a `shouldRun` flag is passed in? If so, I don't think it's necessary to throw an exception, as this limitation will be reflected in the documentation

2024-01-05 12:20 UTC, jftuduri commented on include/HTTPRequest.hpp
> +     * @param shouldRun Flag used to interrupt the handler.
That's ok. I just listed different options.

2024-01-05 14:52 UTC, kevin-mcm commented on include/HTTPRequest.hpp
> +    void customDownload(
done

2024-01-05 14:52 UTC, kevin-mcm commented on include/HTTPRequest.hpp
> +     * @param shouldRun Flag used to interrupt the handler.
done

2024-01-09 21:45 UTC, kevin-mcm commented on test/component/component_test.cpp
> +    std::this_thread::sleep_for(std::chrono::seconds(sleepMainThread));
done

2024-01-09 21:45 UTC, kevin-mcm commented on test/component/component_test.hpp
> +        m_server.Get(R"(/custom-download/(\d+))",
done

2024-01-09 21:45 UTC, kevin-mcm commented on include/curlMultiHandler.hpp
> +    void execute() override
done

2024-01-09 23:41 UTC, kevin-mcm commented on test/unit/curlHandlerCache_test.cpp
done

2024-01-10 12:20 UTC, tsarquis88 reviewed
I have just one last concern.

I've made a test where a file download was interrupted in the middle and after the interruption, the output file was present in the filesystem with the content downloaded to that moment (an incomplete file).

My question is, shouldn't we take care of this file? For example, by removing it if the download was not complete?

Isn't there an 'official' way of canceling a download, maybe through libcurl?

2024-01-29 17:22 UTC, Damian-Mangold commented
> I have just one last concern.
> 
> I've made a test where a file download was interrupted in the middle and after the interruption, the output file was present in the filesystem with the content downloaded to that moment (an incomplete file).
> 
> My question is, shouldn't we take care of this file? For example, by removing it if the download was not complete?
> 
> Isn't there an 'official' way of canceling a download, maybe through libcurl?

From what Kevin said, there is no way to delete partially downloaded content using libcurl, so the user using the library would be responsible for deleting the content if they do not intend to keep it stored in case of download interruption.

2024-01-29 17:37 UTC, tsarquis88 submitted a review, later dismissed
LGTM!

2024-01-29 18:01 UTC, Damian-Mangold submitted a review, later dismissed
LGTM

2024-02-08 23:42 UTC, Damian-Mangold approved these changes
LGTM

2024-02-09 02:12 UTC, Dwordcito approved these changes

2024-02-09 02:12 UTC, merged