Refactor: Improve parameters interface
wazuh/wazuh-http-request pull request #62
Opened 2024-08-01 02:35 UTC by pereyra-m

| Related issue |
|--------|
| Closes #60 |

## Description

This PR updates all the interfaces to make them more clear to be used and read. Also, future additions of parameters should be easier and will require less time to be implemented.

Some references were considered for the refactor ([How to Design Function Parameters That Make Interfaces Easier to Use - Fluent C++](https://www.fluentcpp.com/2018/11/23/function-parameters-making-interfaces-easy-to-use/)).
The proposal divides the parameters in three categories: general parameters that will be used in the query itself (what to do), optional configuration parameters to tune the behavior of the query (how to do it), and post-request parameters to define actions to take with the query results (what to after).

Each category is a structure, and only the first one is mandatory. This simplifies the simpler calls, and avoid writing unnecessary default values.
For the most complex method calls, each field name is used, making the read eaiser.

## Examples

Here we have the most representative examples of the implementation, comparing the current approach against the new one.

<details><summary>Only required parameters are written</summary>
<p>

Here we don't need to write all the empty curly braces and only the three meaningful fields are written

![2024-07-31_23-27](https://github.com/user-attachments/assets/8aa5ce6c-b6c8-4c05-893a-1824a416be7d)

</p>
</details> 

<details><summary>Each parameter has its name</summary>
<p>

The lambda parameters can be confused, but now that each one has its name, they can't.
Also, the configuration structure can be committed because it doesn't contain relevant parameters for this call.

![2024-07-31_23-30](https://github.com/user-attachments/assets/2a640d8f-3339-4065-916a-9d6da0a58b50)

</p>
</details>

2024-08-01 18:43 UTC, sebasfalcone requested changes
Great work @pereyra-m!

Just some details

2024-08-01 18:43 UTC, sebasfalcone commented on src/HTTPRequest.cpp
> +    const auto& shouldRun {configurationParameters.shouldRun};
Note: I think this could initialized using structure bindings, but the solution was not as simple. [Here](https://github.com/wazuh/wazuh-http-request/compare/enhancement/60-improve-parameters-interface...tmp/structure_bindings_demonstration) you can see how it would be implemented

2024-08-01 18:43 UTC, sebasfalcone commented on src/UNIXSocketRequest.cpp
> +                               : std::get<nlohmann::json>(requestParameters.data).dump();
Improve: Use of const
```suggestion
        const std::string data = std::holds_alternative<std::string>(requestParameters.data)
                                     ? std::get<std::string>(requestParameters.data)
                                     : std::get<nlohmann::json>(requestParameters.data).dump();
```

2024-08-01 18:43 UTC, sebasfalcone commented on include/IURLRequest.hpp
> + * error handling, results processing, etc. They can be thought of as "what to do after".
+1: This is really well documented

2024-08-01 18:43 UTC, sebasfalcone commented on src/HTTPRequest.cpp
> +        std::string data = std::holds_alternative<std::string>(requestParameters.data)
Improve: Use of const
```suggestion
        const std::string data = std::holds_alternative<std::string>(requestParameters.data)
                                     ? std::get<std::string>(requestParameters.data)
                                     : std::get<nlohmann::json>(requestParameters.data).dump();
```

2024-08-01 18:43 UTC, sebasfalcone commented on src/HTTPRequest.cpp
> +        std::string data = std::holds_alternative<std::string>(requestParameters.data)
Improve: Use of const
```suggestion
        const std::string data = std::holds_alternative<std::string>(requestParameters.data)
                                     ? std::get<std::string>(requestParameters.data)
                                     : std::get<nlohmann::json>(requestParameters.data).dump();
```

2024-08-01 18:43 UTC, sebasfalcone commented on src/HTTPRequest.cpp
> +        std::string data = std::holds_alternative<std::string>(requestParameters.data)
Improve: Use of const
```suggestion
        const std::string data = std::holds_alternative<std::string>(requestParameters.data)
                                     ? std::get<std::string>(requestParameters.data)
                                     : std::get<nlohmann::json>(requestParameters.data).dump();
```

2024-08-01 18:43 UTC, sebasfalcone commented on src/UNIXSocketRequest.cpp
> +        std::string data = std::holds_alternative<std::string>(requestParameters.data)
Improve: Use of const
```suggestion
        const std::string data = std::holds_alternative<std::string>(requestParameters.data)
                                     ? std::get<std::string>(requestParameters.data)
                                     : std::get<nlohmann::json>(requestParameters.data).dump();
```

2024-08-01 18:43 UTC, sebasfalcone commented on src/UNIXSocketRequest.cpp
> +        std::string data = std::holds_alternative<std::string>(requestParameters.data)
Improve: Use of const
```suggestion
        const std::string data = std::holds_alternative<std::string>(requestParameters.data)
                                     ? std::get<std::string>(requestParameters.data)
                                     : std::get<nlohmann::json>(requestParameters.data).dump();
```

2024-08-01 18:43 UTC, sebasfalcone commented on test/benchmark/main.cpp
> +            RequestParameters {.url = HttpURL("http://localhost:44441/12345"), .data = R"({"foo": "bar"})"_json});
Question: Was the addition of `12345` on purpose? 
```suggestion
            RequestParameters {.url = HttpURL("http://localhost:44441/12345"), .data = R"({"foo": "bar"})"_json});
```

2024-08-01 22:59 UTC, pereyra-m commented on src/HTTPRequest.cpp
> +    const auto& shouldRun {configurationParameters.shouldRun};
We can improve this section indeed, because it's too verbose.
The use of structure binding makes it much cleaner. But I see some drawbacks:
- That approach depends on the order of the parameters of the structure, changing it in the future could introduce hidden errors.
- Future additions of parameters in the structures force us to update all the unpacking lines all over the code, because the number of parameters must always match the number of variables.

What do you think of this instead? I considered it at first, but I wasn't sure if it was clear enough.
I have to add the names of the structures many times, but we get rid of the verbose unpacking.

```c++
        GetRequest::builder(FactoryRequestWrapper<wrapperType>::create(configurationParameters.handlerType,
                                                                       configurationParameters.shouldRun))
            .url(requestParameters.url.url(), requestParameters.secureCommunication)
            .outputFile(postRequestParameters.outputFile)
            .appendHeaders(requestParameters.httpHeaders)
            .userAgent(configurationParameters.userAgent)
            .execute();
    }
```

2024-08-01 23:02 UTC, pereyra-m commented on src/UNIXSocketRequest.cpp
> +                               : std::get<nlohmann::json>(requestParameters.data).dump();
Thank you!
Fixed

2024-08-01 23:02 UTC, pereyra-m commented on src/HTTPRequest.cpp
> +        std::string data = std::holds_alternative<std::string>(requestParameters.data)
Thank you!
Fixed

2024-08-01 23:02 UTC, pereyra-m commented on src/HTTPRequest.cpp
> +        std::string data = std::holds_alternative<std::string>(requestParameters.data)
Thank you!
Fixed

2024-08-01 23:02 UTC, pereyra-m commented on src/HTTPRequest.cpp
> +        std::string data = std::holds_alternative<std::string>(requestParameters.data)
Thank you!
Fixed

2024-08-01 23:02 UTC, pereyra-m commented on src/UNIXSocketRequest.cpp
> +        std::string data = std::holds_alternative<std::string>(requestParameters.data)
Thank you!
Fixed

2024-08-01 23:02 UTC, pereyra-m commented on src/UNIXSocketRequest.cpp
> +        std::string data = std::holds_alternative<std::string>(requestParameters.data)
Thank you!
Fixed

2024-08-01 23:04 UTC, pereyra-m commented on test/benchmark/main.cpp
> +            RequestParameters {.url = HttpURL("http://localhost:44441/12345"), .data = R"({"foo": "bar"})"_json});
Good catch!
Copy-paste mistake, fixed.

2024-08-01 23:45 UTC, sebasfalcone requested changes

2024-08-01 23:45 UTC, sebasfalcone commented on src/UNIXSocketRequest.cpp
> +    std::string data;
Improve: This can be removed

2024-08-01 23:46 UTC, sebasfalcone commented on src/HTTPRequest.cpp
> +    const auto& shouldRun {configurationParameters.shouldRun};
> That approach depends on the order of the parameters of the structure, changing it in the future could introduce hidden errors.

I think you are right, the current approach is much cleaner

2024-08-02 00:54 UTC, pereyra-m commented on src/UNIXSocketRequest.cpp
> +    std::string data;
Thank you, removed!

2024-08-05 02:44 UTC, sebasfalcone approved these changes

2024-08-12 01:56 UTC, merged