Adding a ms timeout configuration parameter
wazuh/wazuh-http-request pull request #64
Opened 2024-08-03 07:41 UTC by pereyra-m

## Description

This PR implements a ms timeout for all the available requests.
Some UT are failing, another issue was created #63.

## Test

<details><summary>Test tool</summary>
<p>

```cmd
root@6f68a3e7a4f3:/workspaces/wazuh-http-request/build/test_tool# ./urlrequest_testtool -u https://httpbin.org/delay/10 -t get --timeout 1000
Timeout was reached: -1
Timeout was reached
```

</p>
</details>

2024-08-06 20:29 UTC, sebasfalcone requested changes

2024-08-06 20:29 UTC, sebasfalcone commented on include/IURLRequest.hpp
> +    const long timeout = 0;
Improve (design): Using a long allows us to set a negative timeout which breaks at runtime

```
[ RUN      ] ComponentTestInterface.DownloadTestTimeoutSingleHandler
/home/sebas/Documents/work/development/wazuh-http-request/test/component/component_test.cpp:1008: Failure
Expected: (std::string::npos) != (std::string(e.what()).find("Timeout was reached")), actual: 18446744073709551615 vs 18446744073709551615
A different exception was thrown: cURLWrapper::setOption() failed
/home/sebas/Documents/work/development/wazuh-http-request/test/component/component_test.cpp:1017: Failure
Expected: (std::string::npos) != (result.find("Timeout was reached")), actual: 18446744073709551615 vs 18446744073709551615
cURLWrapper::setOption() failed
[  FAILED  ] ComponentTestInterface.DownloadTestTimeoutSingleHandler (0 ms)
```

We should instead use an unsigned long

2024-08-06 20:29 UTC, sebasfalcone commented on include/IURLRequest.hpp
> +    const long timeout = 0;
Using unsigned long
```
/home/sebas/Documents/work/development/wazuh-http-request/test/component/component_test.cpp: In member function ‘virtual void ComponentTestInterface_DownloadTestTimeoutSingleHandler_Test::TestBody()’:
/home/sebas/Documents/work/development/wazuh-http-request/test/component/component_test.cpp:1019:52: error: narrowing conversion of ‘-10’ from ‘int’ to ‘long unsigned int’ [-Wnarrowing]
 1019 |             ConfigurationParameters {.timeout = -10});
      |                                                    ^
ninja: build stopped: subcommand failed.
```

2024-08-08 03:02 UTC, pereyra-m commented on include/IURLRequest.hpp
> +    const long timeout = 0;
Hi @sebasfalcone 

I was unable to reproduce this exception, using the `CURLOPT_TIMEOUT_MS` option. I had to modify it to the previous `CURLOPT_TIMEOUT` to make it fail. 
Maybe this is because internally , the options behave in a different way

https://curl.se/libcurl/c/CURLOPT_TIMEOUT.html

> Returns [CURLE_OK](https://curl.se/libcurl/c/libcurl-errors.html#CURLEOK). Returns [CURLE_BAD_FUNCTION_ARGUMENT](https://curl.se/libcurl/c/libcurl-errors.html#CURLEBADFUNCTIONARGUMENT) if set to a negative value or a value that when converted to milliseconds is too large.

https://curl.se/libcurl/c/CURLOPT_TIMEOUT_MS.html

> Returns [CURLE_OK](https://curl.se/libcurl/c/libcurl-errors.html#CURLEOK)

On the other hand, the `curl_easy_setopt()` method (https://curl.se/libcurl/c/curl_easy_setopt.html) allows `long` as a parameter type. Setting an `unsigned long` might introduce type conversion errors.

2024-08-08 23:47 UTC, sebasfalcone approved these changes
### Tests
I created a server using the following script
```py
import http.server
import socketserver
import time

PORT = 8080
DELAY = 5  # delay in seconds

class MyRequestHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        # Introduce a delay before responding
        time.sleep(DELAY)
        
        # Send response status code
        self.send_response(200)
        
        # Send headers
        self.send_header('Content-type', 'text/html')
        self.end_headers()
        
        # Write the content as utf-8 data
        self.wfile.write(bytes("Hello, world! You've waited for {} seconds.".format(DELAY), "utf8"))

    def do_POST(self):
        # Introduce a delay before responding
        time.sleep(DELAY)
        
        # Read the length of the content
        content_length = int(self.headers['Content-Length'])
        post_data = self.rfile.read(content_length)
        
        # Send response status code
        self.send_response(200)
        
        # Send headers
        self.send_header('Content-type', 'text/html')
        self.end_headers()
        
        # Write the content as utf-8 data
        self.wfile.write(bytes("Received POST data: {}".format(post_data.decode("utf-8")), "utf8"))

with socketserver.TCPServer(("", PORT), MyRequestHandler) as httpd:
    print("Serving on port", PORT)
    httpd.serve_forever()
```
The server waits for 5 seconds to respond

### No timeout
```
./urlrequest_testtool -u 127.0.0.1:8080 -t get
Hello, world! You've waited for 5 seconds.

./urlrequest_testtool -u 127.0.0.1:8080 -t post
Received POST data: 
```

### Timeout less than 5 seconds
```
./urlrequest_testtool -u 127.0.0.1:8080 -t get --timeout 1000
Timeout was reached: -1
Timeout was reached

./urlrequest_testtool -u 127.0.0.1:8080 -t post --timeout 1000
Timeout was reached: -1
Timeout was reached
```

### Timeout greater than 5 seconds
```
./urlrequest_testtool -u 127.0.0.1:8080 -t get --timeout 10000
Hello, world! You've waited for 5 seconds.

./urlrequest_testtool -u 127.0.0.1:8080 -t post --timeout 10000
Received POST data: 
```

2024-08-09 00:23 UTC, sebasfalcone submitted a review, later dismissed

2024-08-09 00:23 UTC, pereyra-m commented on src/HTTPRequest.cpp
> +        }
But I could't apply it due to `cppcheck`

2024-08-09 00:23 UTC, pereyra-m commented on src/HTTPRequest.cpp
> +        }
But I could't apply it due to `cppcheck`

2024-08-19 14:00 UTC, merged